[profile]
default = { libs = ["node_modules", "lib"], solc = "0.8.17"}
[profile.test]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
solc_version = '0.8.17'
remapping = [
                'ds-test/=lib/forge-std/lib/ds-test/src/',
                'forge-std/=lib/forge-std/src/',
    ]
[rpc_endpoints]
mainnet = "${RPC_MAINNET}"
